<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../Fixtures/CubeMxFixture.cs" Link="CubeMxFixture.cs" />
    <ProjectReference Include="../../src/CMakeDapLink.App/CMakeDapLink.App.csproj" />
  </ItemGroup>
</Project>
